#!/bin/sh

CONDA_ENV_PATH=/home/ruhyadi/miniconda3/envs
CONDA_ENV_NAME=vision
WHERE_OPENCV=../opencv-4.1.2
WHERE_OPENCV_CONTRIB=../opencv_contrib-4.1.2

cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D PYTHON3_EXECUTABLE=$CONDA_ENV_PATH/$CONDA_ENV_NAME/bin/python \
	-D INSTALL_C_EXAMPLES=OFF \
	-D INSTALL_PYTHON_EXAMPLES=OFF \
	-D OPENCV_EXTRA_MODULES_PATH=$WHERE_OPENCV_CONTRIB/modules \
	-D WITH_QT=ON \
	-D OPENCV_GENERATE_PKGCONFIG=ON \
	-D OPENCV_ENABLE_NONFREE=ON \
	-D BUILD_EXAMPLES=ON $WHERE_OPENCV